/*
 * Created on 28 ago 2017 ( Time 17:50:57 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.tuin.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.math.BigDecimal;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "clienteviajeservicio"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="clienteviajeservicio", catalog="app" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ClienteviajeservicioEntity.countAll", query="SELECT COUNT(x) FROM ClienteviajeservicioEntity x" )
} )
public class ClienteviajeservicioEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Long       id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="cantidad", nullable=false)
    private Integer    cantidad     ;

    @Column(name="costo", nullable=false)
    private BigDecimal costo        ;

	// "clienteviajeid" (column "clienteViajeId") is not defined by itself because used as FK in a link 
	// "vehiculoservicioid" (column "vehiculoServicioId") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="clienteViajeId", referencedColumnName="id")
    private ClienteviajeEntity clienteviaje;

    @ManyToOne
    @JoinColumn(name="vehiculoServicioId", referencedColumnName="id")
    private VehiculoservicioEntity vehiculoservicio;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ClienteviajeservicioEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : cantidad ( INT ) 
    public void setCantidad( Integer cantidad ) {
        this.cantidad = cantidad;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }

    //--- DATABASE MAPPING : costo ( DECIMAL ) 
    public void setCosto( BigDecimal costo ) {
        this.costo = costo;
    }
    public BigDecimal getCosto() {
        return this.costo;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setClienteviaje( ClienteviajeEntity clienteviaje ) {
        this.clienteviaje = clienteviaje;
    }
    public ClienteviajeEntity getClienteviaje() {
        return this.clienteviaje;
    }

    public void setVehiculoservicio( VehiculoservicioEntity vehiculoservicio ) {
        this.vehiculoservicio = vehiculoservicio;
    }
    public VehiculoservicioEntity getVehiculoservicio() {
        return this.vehiculoservicio;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(cantidad);
        sb.append("|");
        sb.append(costo);
        return sb.toString(); 
    } 

}
