/*
 * Created on 28 ago 2017 ( Time 17:50:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.tuin.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "cliente"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="cliente", catalog="app" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ClienteEntity.countAll", query="SELECT COUNT(x) FROM ClienteEntity x" )
} )
public class ClienteEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Long       id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	// "entidadid" (column "entidadId") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="cliente", targetEntity=ClienteviajeEntity.class)
    private List<ClienteviajeEntity> listOfClienteviaje;

    @ManyToOne
    @JoinColumn(name="entidadId", referencedColumnName="id")
    private EntidadEntity entidad     ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ClienteEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfClienteviaje( List<ClienteviajeEntity> listOfClienteviaje ) {
        this.listOfClienteviaje = listOfClienteviaje;
    }
    public List<ClienteviajeEntity> getListOfClienteviaje() {
        return this.listOfClienteviaje;
    }

    public void setEntidad( EntidadEntity entidad ) {
        this.entidad = entidad;
    }
    public EntidadEntity getEntidad() {
        return this.entidad;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        return sb.toString(); 
    } 

}
