/*
 * Created on 28 ago 2017 ( Time 17:50:59 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.tuin.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "facturaelectronica"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="facturaelectronica", catalog="app" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="FacturaelectronicaEntity.countAll", query="SELECT COUNT(x) FROM FacturaelectronicaEntity x" )
} )
public class FacturaelectronicaEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Long       id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="claveAcceso", nullable=false, length=100)
    private String     claveacceso  ;

    @Column(name="respuesta", nullable=false, length=200)
    private String     respuesta    ;

    @Temporal(TemporalType.DATE)
    @Column(name="fechaAutorizacion", nullable=false)
    private Date       fechaautorizacion ;

	// "estadoid" (column "estadoId") is not defined by itself because used as FK in a link 
	// "documentoid" (column "documentoId") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="estadoId", referencedColumnName="id")
    private EstadoEntity estado      ;

    @ManyToOne
    @JoinColumn(name="documentoId", referencedColumnName="id")
    private DocumentoEntity documento   ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public FacturaelectronicaEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : claveAcceso ( VARCHAR ) 
    public void setClaveacceso( String claveacceso ) {
        this.claveacceso = claveacceso;
    }
    public String getClaveacceso() {
        return this.claveacceso;
    }

    //--- DATABASE MAPPING : respuesta ( VARCHAR ) 
    public void setRespuesta( String respuesta ) {
        this.respuesta = respuesta;
    }
    public String getRespuesta() {
        return this.respuesta;
    }

    //--- DATABASE MAPPING : fechaAutorizacion ( DATE ) 
    public void setFechaautorizacion( Date fechaautorizacion ) {
        this.fechaautorizacion = fechaautorizacion;
    }
    public Date getFechaautorizacion() {
        return this.fechaautorizacion;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setEstado( EstadoEntity estado ) {
        this.estado = estado;
    }
    public EstadoEntity getEstado() {
        return this.estado;
    }

    public void setDocumento( DocumentoEntity documento ) {
        this.documento = documento;
    }
    public DocumentoEntity getDocumento() {
        return this.documento;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(claveacceso);
        sb.append("|");
        sb.append(respuesta);
        sb.append("|");
        sb.append(fechaautorizacion);
        return sb.toString(); 
    } 

}
