/*
 * Created on 28 ago 2017 ( Time 17:51:02 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.tuin.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "variables"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="variables", catalog="app" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="VariablesEntity.countAll", query="SELECT COUNT(x) FROM VariablesEntity x" )
} )
public class VariablesEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Long       id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="contenido", nullable=false, length=200)
    private String     contenido    ;

    @Column(name="activa", nullable=false)
    private Byte       activa       ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public VariablesEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : contenido ( VARCHAR ) 
    public void setContenido( String contenido ) {
        this.contenido = contenido;
    }
    public String getContenido() {
        return this.contenido;
    }

    //--- DATABASE MAPPING : activa ( TINYINT ) 
    public void setActiva( Byte activa ) {
        this.activa = activa;
    }
    public Byte getActiva() {
        return this.activa;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(contenido);
        sb.append("|");
        sb.append(activa);
        return sb.toString(); 
    } 

}
