/*
 * Created on 28 ago 2017 ( Time 17:51:03 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.tuin.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "viaje"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="viaje", catalog="app" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ViajeEntity.countAll", query="SELECT COUNT(x) FROM ViajeEntity x" )
} )
public class ViajeEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Long       id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="confirmado", nullable=false)
    private Byte       confirmado   ;

	// "destinohorarioid" (column "destinoHorarioId") is not defined by itself because used as FK in a link 
	// "chofervehiculoid" (column "choferVehiculoId") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="choferVehiculoId", referencedColumnName="id")
    private ChofervehiculoEntity chofervehiculo;

    @ManyToOne
    @JoinColumn(name="destinoHorarioId", referencedColumnName="id")
    private DestinohorarioEntity destinohorario;

    @OneToMany(mappedBy="viaje", targetEntity=ClienteviajeEntity.class)
    private List<ClienteviajeEntity> listOfClienteviaje;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ViajeEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : confirmado ( TINYINT ) 
    public void setConfirmado( Byte confirmado ) {
        this.confirmado = confirmado;
    }
    public Byte getConfirmado() {
        return this.confirmado;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setChofervehiculo( ChofervehiculoEntity chofervehiculo ) {
        this.chofervehiculo = chofervehiculo;
    }
    public ChofervehiculoEntity getChofervehiculo() {
        return this.chofervehiculo;
    }

    public void setDestinohorario( DestinohorarioEntity destinohorario ) {
        this.destinohorario = destinohorario;
    }
    public DestinohorarioEntity getDestinohorario() {
        return this.destinohorario;
    }

    public void setListOfClienteviaje( List<ClienteviajeEntity> listOfClienteviaje ) {
        this.listOfClienteviaje = listOfClienteviaje;
    }
    public List<ClienteviajeEntity> getListOfClienteviaje() {
        return this.listOfClienteviaje;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(confirmado);
        return sb.toString(); 
    } 

}
