
/*
 * Created on 28 ago 2017 ( Time 17:50:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.mock;

import java.util.LinkedList;
import java.util.List;

import com.tuin.bean.jpa.ClienteviajeEntity;
import com.tuin.mock.tool.MockValues;

public class ClienteviajeEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public ClienteviajeEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextLong() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public ClienteviajeEntity createInstance( Long id ) {
		ClienteviajeEntity entity = new ClienteviajeEntity();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setLatitud( mockValues.nextBigDecimal() ) ; // java.math.BigDecimal 
		entity.setLongitud( mockValues.nextBigDecimal() ) ; // java.math.BigDecimal 
		entity.setPasajeros( mockValues.nextInteger() ) ; // java.lang.Integer 
		entity.setCosto( mockValues.nextBigDecimal() ) ; // java.math.BigDecimal 
		// Init Link fields (if any)
		// setViaje( TODO ) ; // Viaje 
		// setCliente( TODO ) ; // Cliente 
		// setEstado( TODO ) ; // Estado 
		// setListOfClienteviajeservicio( TODO ) ; // List<Clienteviajeservicio> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<ClienteviajeEntity> createList(int count) {
		List<ClienteviajeEntity> list = new LinkedList<ClienteviajeEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
