
/*
 * Created on 28 ago 2017 ( Time 17:50:58 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.mock;

import java.util.LinkedList;
import java.util.List;

import com.tuin.bean.jpa.DestinohorarioEntity;
import com.tuin.mock.tool.MockValues;

public class DestinohorarioEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public DestinohorarioEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextLong() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public DestinohorarioEntity createInstance( Long id ) {
		DestinohorarioEntity entity = new DestinohorarioEntity();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setCosto( mockValues.nextBigDecimal() ) ; // java.math.BigDecimal 
		entity.setMinimopasajeros( mockValues.nextInteger() ) ; // java.lang.Integer 
		entity.setAutomatico( mockValues.nextByte() ) ; // java.lang.Byte 
		// Init Link fields (if any)
		// setCiudad( TODO ) ; // Ciudad 
		// setHorario( TODO ) ; // Horario 
		// setListOfViaje( TODO ) ; // List<Viaje> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<DestinohorarioEntity> createList(int count) {
		List<DestinohorarioEntity> list = new LinkedList<DestinohorarioEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
