
/*
 * Created on 28 ago 2017 ( Time 17:50:58 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.mock;

import java.util.LinkedList;
import java.util.List;

import com.tuin.bean.jpa.EntidadrolEntity;
import com.tuin.mock.tool.MockValues;

public class EntidadrolEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public EntidadrolEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextLong() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public EntidadrolEntity createInstance( Long id ) {
		EntidadrolEntity entity = new EntidadrolEntity();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		// Init Link fields (if any)
		// setRol( TODO ) ; // Rol 
		// setEntidad( TODO ) ; // Entidad 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<EntidadrolEntity> createList(int count) {
		List<EntidadrolEntity> list = new LinkedList<EntidadrolEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
