
/*
 * Created on 28 ago 2017 ( Time 17:51:00 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.mock;

import java.util.LinkedList;
import java.util.List;

import com.tuin.bean.jpa.ItemmenuEntity;
import com.tuin.mock.tool.MockValues;

public class ItemmenuEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public ItemmenuEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextLong() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public ItemmenuEntity createInstance( Long id ) {
		ItemmenuEntity entity = new ItemmenuEntity();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setLink( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setNombre( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setOrden( mockValues.nextInteger() ) ; // java.lang.Integer 
		entity.setActivo( mockValues.nextByte() ) ; // java.lang.Byte 
		// Init Link fields (if any)
		// setListOfRolitemmenu( TODO ) ; // List<Rolitemmenu> 
		// setMenu( TODO ) ; // Menu 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<ItemmenuEntity> createList(int count) {
		List<ItemmenuEntity> list = new LinkedList<ItemmenuEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
