/*
 * Created on 28 ago 2017 ( Time 17:51:19 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.business.service.impl;

import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;

import javax.annotation.Resource;

import com.tuin.bean.Tipocomponentefinanciero;
import com.tuin.bean.jpa.TipocomponentefinancieroEntity;
import java.util.List;
import com.tuin.business.service.TipocomponentefinancieroService;
import com.tuin.business.service.mapping.TipocomponentefinancieroServiceMapper;
import com.tuin.persistence.PersistenceServiceProvider;
import com.tuin.persistence.services.TipocomponentefinancieroPersistence;
import org.springframework.stereotype.Component;

/**
 * Implementation of TipocomponentefinancieroService
 */
@Component
public class TipocomponentefinancieroServiceImpl implements TipocomponentefinancieroService {

	private TipocomponentefinancieroPersistence tipocomponentefinancieroPersistence;

	@Resource
	private TipocomponentefinancieroServiceMapper tipocomponentefinancieroServiceMapper;
	
	public TipocomponentefinancieroServiceImpl() {
		tipocomponentefinancieroPersistence = PersistenceServiceProvider.getService(TipocomponentefinancieroPersistence.class);
	}
		
	@Override
	public Tipocomponentefinanciero findById(Long id) {
		TipocomponentefinancieroEntity entity = tipocomponentefinancieroPersistence.load(id);
		return tipocomponentefinancieroServiceMapper.mapTipocomponentefinancieroEntityToTipocomponentefinanciero(entity);
	}

	@Override
	public List<Tipocomponentefinanciero> findAll() {
		List<TipocomponentefinancieroEntity> entities = tipocomponentefinancieroPersistence.loadAll();
		List<Tipocomponentefinanciero> beans = new ArrayList<Tipocomponentefinanciero>();
		for(TipocomponentefinancieroEntity entity : entities) {
			beans.add(tipocomponentefinancieroServiceMapper.mapTipocomponentefinancieroEntityToTipocomponentefinanciero(entity));
		}
		return beans;
	}

	@Override
	public Tipocomponentefinanciero save(Tipocomponentefinanciero tipocomponentefinanciero) {
		return update(tipocomponentefinanciero) ;
	}

	@Override
	public Tipocomponentefinanciero create(Tipocomponentefinanciero tipocomponentefinanciero) {
		if(tipocomponentefinancieroPersistence.load(tipocomponentefinanciero.getId()) != null) {
			throw new IllegalStateException("already.exists");
		}
		TipocomponentefinancieroEntity tipocomponentefinancieroEntity = new TipocomponentefinancieroEntity();
		tipocomponentefinancieroServiceMapper.mapTipocomponentefinancieroToTipocomponentefinancieroEntity(tipocomponentefinanciero, tipocomponentefinancieroEntity);
		TipocomponentefinancieroEntity tipocomponentefinancieroEntitySaved = tipocomponentefinancieroPersistence.save(tipocomponentefinancieroEntity);
		return tipocomponentefinancieroServiceMapper.mapTipocomponentefinancieroEntityToTipocomponentefinanciero(tipocomponentefinancieroEntitySaved);
	}

	@Override
	public Tipocomponentefinanciero update(Tipocomponentefinanciero tipocomponentefinanciero) {
		TipocomponentefinancieroEntity tipocomponentefinancieroEntity = tipocomponentefinancieroPersistence.load(tipocomponentefinanciero.getId());
		tipocomponentefinancieroServiceMapper.mapTipocomponentefinancieroToTipocomponentefinancieroEntity(tipocomponentefinanciero, tipocomponentefinancieroEntity);
		TipocomponentefinancieroEntity tipocomponentefinancieroEntitySaved = tipocomponentefinancieroPersistence.save(tipocomponentefinancieroEntity);
		return tipocomponentefinancieroServiceMapper.mapTipocomponentefinancieroEntityToTipocomponentefinanciero(tipocomponentefinancieroEntitySaved);
	}

	@Override
	public void delete(Long id) {
		tipocomponentefinancieroPersistence.delete(id);
	}

	public TipocomponentefinancieroPersistence getTipocomponentefinancieroPersistence() {
		return tipocomponentefinancieroPersistence;
	}

	public void setTipocomponentefinancieroPersistence(TipocomponentefinancieroPersistence tipocomponentefinancieroPersistence) {
		this.tipocomponentefinancieroPersistence = tipocomponentefinancieroPersistence;
	}

	public TipocomponentefinancieroServiceMapper getTipocomponentefinancieroServiceMapper() {
		return tipocomponentefinancieroServiceMapper;
	}

	public void setTipocomponentefinancieroServiceMapper(TipocomponentefinancieroServiceMapper tipocomponentefinancieroServiceMapper) {
		this.tipocomponentefinancieroServiceMapper = tipocomponentefinancieroServiceMapper;
	}

}
