/*
 * Created on 28 ago 2017 ( Time 17:51:13 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.tuin.bean.Cliente;
import com.tuin.bean.jpa.ClienteEntity;
import com.tuin.bean.jpa.EntidadEntity;
import com.tuin.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class ClienteServiceMapperTest {

	private ClienteServiceMapper clienteServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		clienteServiceMapper = new ClienteServiceMapper();
		clienteServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'ClienteEntity' to 'Cliente'
	 * @param clienteEntity
	 */
	@Test
	public void testMapClienteEntityToCliente() {
		// Given
		ClienteEntity clienteEntity = new ClienteEntity();
		clienteEntity.setEntidad(new EntidadEntity());
		clienteEntity.getEntidad().setId(mockValues.nextLong());
		
		// When
		Cliente cliente = clienteServiceMapper.mapClienteEntityToCliente(clienteEntity);
		
		// Then
		assertEquals(clienteEntity.getEntidad().getId(), cliente.getEntidadid());
	}
	
	/**
	 * Test : Mapping from 'Cliente' to 'ClienteEntity'
	 */
	@Test
	public void testMapClienteToClienteEntity() {
		// Given
		Cliente cliente = new Cliente();
		cliente.setEntidadid(mockValues.nextLong());

		ClienteEntity clienteEntity = new ClienteEntity();
		
		// When
		clienteServiceMapper.mapClienteToClienteEntity(cliente, clienteEntity);
		
		// Then
		assertEquals(cliente.getEntidadid(), clienteEntity.getEntidad().getId());
	}

}