/*
 * Created on 28 ago 2017 ( Time 17:51:16 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.tuin.bean.Formapagodocumento;
import com.tuin.bean.jpa.FormapagodocumentoEntity;
import com.tuin.bean.jpa.DocumentoEntity;
import com.tuin.bean.jpa.FormapagoEntity;
import com.tuin.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class FormapagodocumentoServiceMapperTest {

	private FormapagodocumentoServiceMapper formapagodocumentoServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		formapagodocumentoServiceMapper = new FormapagodocumentoServiceMapper();
		formapagodocumentoServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'FormapagodocumentoEntity' to 'Formapagodocumento'
	 * @param formapagodocumentoEntity
	 */
	@Test
	public void testMapFormapagodocumentoEntityToFormapagodocumento() {
		// Given
		FormapagodocumentoEntity formapagodocumentoEntity = new FormapagodocumentoEntity();
		formapagodocumentoEntity.setDocumento(new DocumentoEntity());
		formapagodocumentoEntity.getDocumento().setId(mockValues.nextLong());
		formapagodocumentoEntity.setFormapago(new FormapagoEntity());
		formapagodocumentoEntity.getFormapago().setId(mockValues.nextLong());
		
		// When
		Formapagodocumento formapagodocumento = formapagodocumentoServiceMapper.mapFormapagodocumentoEntityToFormapagodocumento(formapagodocumentoEntity);
		
		// Then
		assertEquals(formapagodocumentoEntity.getDocumento().getId(), formapagodocumento.getDocumentoid());
		assertEquals(formapagodocumentoEntity.getFormapago().getId(), formapagodocumento.getFormapagoid());
	}
	
	/**
	 * Test : Mapping from 'Formapagodocumento' to 'FormapagodocumentoEntity'
	 */
	@Test
	public void testMapFormapagodocumentoToFormapagodocumentoEntity() {
		// Given
		Formapagodocumento formapagodocumento = new Formapagodocumento();
		formapagodocumento.setDocumentoid(mockValues.nextLong());
		formapagodocumento.setFormapagoid(mockValues.nextLong());

		FormapagodocumentoEntity formapagodocumentoEntity = new FormapagodocumentoEntity();
		
		// When
		formapagodocumentoServiceMapper.mapFormapagodocumentoToFormapagodocumentoEntity(formapagodocumento, formapagodocumentoEntity);
		
		// Then
		assertEquals(formapagodocumento.getDocumentoid(), formapagodocumentoEntity.getDocumento().getId());
		assertEquals(formapagodocumento.getFormapagoid(), formapagodocumentoEntity.getFormapago().getId());
	}

}