/*
 * Created on 28 ago 2017 ( Time 17:51:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.tuin.bean.Menu;
import com.tuin.bean.jpa.MenuEntity;
import com.tuin.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class MenuServiceMapperTest {

	private MenuServiceMapper menuServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		menuServiceMapper = new MenuServiceMapper();
		menuServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'MenuEntity' to 'Menu'
	 * @param menuEntity
	 */
	@Test
	public void testMapMenuEntityToMenu() {
		// Given
		MenuEntity menuEntity = new MenuEntity();
		menuEntity.setNombre(mockValues.nextString(45));
		menuEntity.setOrden(mockValues.nextString(45));
		menuEntity.setActivo(mockValues.nextByte());
		
		// When
		Menu menu = menuServiceMapper.mapMenuEntityToMenu(menuEntity);
		
		// Then
		assertEquals(menuEntity.getNombre(), menu.getNombre());
		assertEquals(menuEntity.getOrden(), menu.getOrden());
		assertEquals(menuEntity.getActivo(), menu.getActivo());
	}
	
	/**
	 * Test : Mapping from 'Menu' to 'MenuEntity'
	 */
	@Test
	public void testMapMenuToMenuEntity() {
		// Given
		Menu menu = new Menu();
		menu.setNombre(mockValues.nextString(45));
		menu.setOrden(mockValues.nextString(45));
		menu.setActivo(mockValues.nextByte());

		MenuEntity menuEntity = new MenuEntity();
		
		// When
		menuServiceMapper.mapMenuToMenuEntity(menu, menuEntity);
		
		// Then
		assertEquals(menu.getNombre(), menuEntity.getNombre());
		assertEquals(menu.getOrden(), menuEntity.getOrden());
		assertEquals(menu.getActivo(), menuEntity.getActivo());
	}

}