/*
 * Created on 28 ago 2017 ( Time 17:51:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.tuin.bean.Modelo;
import com.tuin.bean.jpa.ModeloEntity;
import com.tuin.bean.jpa.MarcaEntity;
import com.tuin.bean.jpa.TipovehiculoEntity;
import com.tuin.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class ModeloServiceMapperTest {

	private ModeloServiceMapper modeloServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		modeloServiceMapper = new ModeloServiceMapper();
		modeloServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'ModeloEntity' to 'Modelo'
	 * @param modeloEntity
	 */
	@Test
	public void testMapModeloEntityToModelo() {
		// Given
		ModeloEntity modeloEntity = new ModeloEntity();
		modeloEntity.setNombre(mockValues.nextString(45));
		modeloEntity.setActivo(mockValues.nextByte());
		modeloEntity.setMarca(new MarcaEntity());
		modeloEntity.getMarca().setId(mockValues.nextLong());
		modeloEntity.setTipovehiculo(new TipovehiculoEntity());
		modeloEntity.getTipovehiculo().setId(mockValues.nextLong());
		
		// When
		Modelo modelo = modeloServiceMapper.mapModeloEntityToModelo(modeloEntity);
		
		// Then
		assertEquals(modeloEntity.getNombre(), modelo.getNombre());
		assertEquals(modeloEntity.getActivo(), modelo.getActivo());
		assertEquals(modeloEntity.getMarca().getId(), modelo.getMarcaid());
		assertEquals(modeloEntity.getTipovehiculo().getId(), modelo.getTipovehiculoid());
	}
	
	/**
	 * Test : Mapping from 'Modelo' to 'ModeloEntity'
	 */
	@Test
	public void testMapModeloToModeloEntity() {
		// Given
		Modelo modelo = new Modelo();
		modelo.setNombre(mockValues.nextString(45));
		modelo.setActivo(mockValues.nextByte());
		modelo.setMarcaid(mockValues.nextLong());
		modelo.setTipovehiculoid(mockValues.nextLong());

		ModeloEntity modeloEntity = new ModeloEntity();
		
		// When
		modeloServiceMapper.mapModeloToModeloEntity(modelo, modeloEntity);
		
		// Then
		assertEquals(modelo.getNombre(), modeloEntity.getNombre());
		assertEquals(modelo.getActivo(), modeloEntity.getActivo());
		assertEquals(modelo.getMarcaid(), modeloEntity.getMarca().getId());
		assertEquals(modelo.getTipovehiculoid(), modeloEntity.getTipovehiculo().getId());
	}

}