/*
 * Created on 28 ago 2017 ( Time 17:51:18 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.tuin.bean.Rol;
import com.tuin.bean.jpa.RolEntity;
import com.tuin.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class RolServiceMapperTest {

	private RolServiceMapper rolServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		rolServiceMapper = new RolServiceMapper();
		rolServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'RolEntity' to 'Rol'
	 * @param rolEntity
	 */
	@Test
	public void testMapRolEntityToRol() {
		// Given
		RolEntity rolEntity = new RolEntity();
		rolEntity.setNombre(mockValues.nextString(45));
		rolEntity.setActivo(mockValues.nextByte());
		
		// When
		Rol rol = rolServiceMapper.mapRolEntityToRol(rolEntity);
		
		// Then
		assertEquals(rolEntity.getNombre(), rol.getNombre());
		assertEquals(rolEntity.getActivo(), rol.getActivo());
	}
	
	/**
	 * Test : Mapping from 'Rol' to 'RolEntity'
	 */
	@Test
	public void testMapRolToRolEntity() {
		// Given
		Rol rol = new Rol();
		rol.setNombre(mockValues.nextString(45));
		rol.setActivo(mockValues.nextByte());

		RolEntity rolEntity = new RolEntity();
		
		// When
		rolServiceMapper.mapRolToRolEntity(rol, rolEntity);
		
		// Then
		assertEquals(rol.getNombre(), rolEntity.getNombre());
		assertEquals(rol.getActivo(), rolEntity.getActivo());
	}

}