/*
 * Created on 28 ago 2017 ( Time 17:51:20 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.tuin.bean.Variables;
import com.tuin.bean.jpa.VariablesEntity;
import com.tuin.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class VariablesServiceMapperTest {

	private VariablesServiceMapper variablesServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		variablesServiceMapper = new VariablesServiceMapper();
		variablesServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'VariablesEntity' to 'Variables'
	 * @param variablesEntity
	 */
	@Test
	public void testMapVariablesEntityToVariables() {
		// Given
		VariablesEntity variablesEntity = new VariablesEntity();
		variablesEntity.setContenido(mockValues.nextString(200));
		variablesEntity.setActiva(mockValues.nextByte());
		
		// When
		Variables variables = variablesServiceMapper.mapVariablesEntityToVariables(variablesEntity);
		
		// Then
		assertEquals(variablesEntity.getContenido(), variables.getContenido());
		assertEquals(variablesEntity.getActiva(), variables.getActiva());
	}
	
	/**
	 * Test : Mapping from 'Variables' to 'VariablesEntity'
	 */
	@Test
	public void testMapVariablesToVariablesEntity() {
		// Given
		Variables variables = new Variables();
		variables.setContenido(mockValues.nextString(200));
		variables.setActiva(mockValues.nextByte());

		VariablesEntity variablesEntity = new VariablesEntity();
		
		// When
		variablesServiceMapper.mapVariablesToVariablesEntity(variables, variablesEntity);
		
		// Then
		assertEquals(variables.getContenido(), variablesEntity.getContenido());
		assertEquals(variables.getActiva(), variablesEntity.getActiva());
	}

}