/*
 * Created on 28 ago 2017 ( Time 17:51:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.web.listitem;

import com.tuin.bean.Formapagodocumento;
import com.tuin.web.common.ListItem;

public class FormapagodocumentoListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public FormapagodocumentoListItem(Formapagodocumento formapagodocumento) {
		super();

		this.value = ""
			 + formapagodocumento.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = formapagodocumento.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
