/*
 * Created on 28 ago 2017 ( Time 17:51:43 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.web.listitem;

import com.tuin.bean.Itemmenu;
import com.tuin.web.common.ListItem;

public class ItemmenuListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public ItemmenuListItem(Itemmenu itemmenu) {
		super();

		this.value = ""
			 + itemmenu.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = itemmenu.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
