/*
 * Created on 28 ago 2017 ( Time 17:51:47 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.web.listitem;

import com.tuin.bean.Vehiculo;
import com.tuin.web.common.ListItem;

public class VehiculoListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public VehiculoListItem(Vehiculo vehiculo) {
		super();

		this.value = ""
			 + vehiculo.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = vehiculo.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
