/*
 * Created on 28 ago 2017 ( Time 17:51:39 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.web.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import com.tuin.web.common.AbstractController;
import com.tuin.web.common.FormMode;
import com.tuin.web.common.Message;
import com.tuin.web.common.MessageType;

//--- Entities
import com.tuin.bean.Componentedocumento;
import com.tuin.bean.Componentefinanciero;
import com.tuin.bean.Documento;

//--- Services 
import com.tuin.business.service.ComponentedocumentoService;
import com.tuin.business.service.ComponentefinancieroService;
import com.tuin.business.service.DocumentoService;

//--- List Items 
import com.tuin.web.listitem.ComponentefinancieroListItem;
import com.tuin.web.listitem.DocumentoListItem;

/**
 * Spring MVC controller for 'Componentedocumento' management.
 */
@Controller
@RequestMapping("/componentedocumento")
public class ComponentedocumentoController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "componentedocumento";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "componentedocumento/form";
	private static final String JSP_LIST   = "componentedocumento/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/componentedocumento/create";
	private static final String SAVE_ACTION_UPDATE   = "/componentedocumento/update";

	//--- Main entity service
	@Resource
    private ComponentedocumentoService componentedocumentoService; // Injected by Spring
	//--- Other service(s)
	@Resource
    private ComponentefinancieroService componentefinancieroService; // Injected by Spring
	@Resource
    private DocumentoService documentoService; // Injected by Spring

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public ComponentedocumentoController() {
		super(ComponentedocumentoController.class, MAIN_ENTITY_NAME );
		log("ComponentedocumentoController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------
	/**
	 * Populates the combo-box "items" for the referenced entity "Componentefinanciero"
	 * @param model
	 */
	private void populateListOfComponentefinancieroItems(Model model) {
		List<Componentefinanciero> list = componentefinancieroService.findAll();
		List<ComponentefinancieroListItem> items = new LinkedList<ComponentefinancieroListItem>();
		for ( Componentefinanciero componentefinanciero : list ) {
			items.add(new ComponentefinancieroListItem( componentefinanciero ) );
		}
		model.addAttribute("listOfComponentefinancieroItems", items ) ;
	}

	/**
	 * Populates the combo-box "items" for the referenced entity "Documento"
	 * @param model
	 */
	private void populateListOfDocumentoItems(Model model) {
		List<Documento> list = documentoService.findAll();
		List<DocumentoListItem> items = new LinkedList<DocumentoListItem>();
		for ( Documento documento : list ) {
			items.add(new DocumentoListItem( documento ) );
		}
		model.addAttribute("listOfDocumentoItems", items ) ;
	}


	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param componentedocumento
	 */
	private void populateModel(Model model, Componentedocumento componentedocumento, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, componentedocumento);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
			populateListOfComponentefinancieroItems(model);
			populateListOfDocumentoItems(model);
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
			populateListOfDocumentoItems(model);
			populateListOfComponentefinancieroItems(model);
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of Componentedocumento found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<Componentedocumento> list = componentedocumentoService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new Componentedocumento
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		Componentedocumento componentedocumento = new Componentedocumento();	
		populateModel( model, componentedocumento, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing Componentedocumento
	 * @param model Spring MVC model
	 * @param id  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{id}")
	public String formForUpdate(Model model, @PathVariable("id") Long id ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		Componentedocumento componentedocumento = componentedocumentoService.findById(id);
		populateModel( model, componentedocumento, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param componentedocumento  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid Componentedocumento componentedocumento, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				Componentedocumento componentedocumentoCreated = componentedocumentoService.create(componentedocumento); 
				model.addAttribute(MAIN_ENTITY_NAME, componentedocumentoCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, componentedocumento.getId() );
			} else {
				populateModel( model, componentedocumento, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "componentedocumento.error.create", e);
			populateModel( model, componentedocumento, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param componentedocumento  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid Componentedocumento componentedocumento, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				Componentedocumento componentedocumentoSaved = componentedocumentoService.update(componentedocumento);
				model.addAttribute(MAIN_ENTITY_NAME, componentedocumentoSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, componentedocumento.getId());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, componentedocumento, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "componentedocumento.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, componentedocumento, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param id  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{id}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("id") Long id) {
		log("Action 'delete'" );
		try {
			componentedocumentoService.delete( id );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "componentedocumento.error.delete", e);
		}
		return redirectToList();
	}

}
