/*
 * Created on 28 ago 2017 ( Time 17:51:40 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.business.service;

import java.util.List;

import com.tuin.bean.Componentefinanciero;

/**
 * Business Service Interface for entity Componentefinanciero.
 */
public interface ComponentefinancieroService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Componentefinanciero findById( Long id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Componentefinanciero> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Componentefinanciero save(Componentefinanciero entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Componentefinanciero update(Componentefinanciero entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Componentefinanciero create(Componentefinanciero entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Long id );


}
