/*
 * Created on 28 ago 2017 ( Time 17:51:40 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.business.service;

import java.util.List;

import com.tuin.bean.Destinohorario;

/**
 * Business Service Interface for entity Destinohorario.
 */
public interface DestinohorarioService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Destinohorario findById( Long id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Destinohorario> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Destinohorario save(Destinohorario entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Destinohorario update(Destinohorario entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Destinohorario create(Destinohorario entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Long id );


}
