/*
 * Created on 28 ago 2017 ( Time 17:51:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.business.service;

import java.util.List;

import com.tuin.bean.Entidad;

/**
 * Business Service Interface for entity Entidad.
 */
public interface EntidadService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Entidad findById( Long id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Entidad> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Entidad save(Entidad entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Entidad update(Entidad entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Entidad create(Entidad entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Long id );


}
