/*
 * Created on 28 ago 2017 ( Time 17:51:43 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.business.service;

import java.util.List;

import com.tuin.bean.Horario;

/**
 * Business Service Interface for entity Horario.
 */
public interface HorarioService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Horario findById( Long id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Horario> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Horario save(Horario entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Horario update(Horario entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Horario create(Horario entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Long id );


}
