/*
 * Created on 28 ago 2017 ( Time 17:51:45 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.business.service;

import java.util.List;

import com.tuin.bean.Rolitemmenu;

/**
 * Business Service Interface for entity Rolitemmenu.
 */
public interface RolitemmenuService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Rolitemmenu findById( Long id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Rolitemmenu> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Rolitemmenu save(Rolitemmenu entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Rolitemmenu update(Rolitemmenu entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Rolitemmenu create(Rolitemmenu entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Long id );


}
