/*
 * Created on 28 ago 2017 ( Time 17:51:45 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.business.service;

import java.util.List;

import com.tuin.bean.Servicio;

/**
 * Business Service Interface for entity Servicio.
 */
public interface ServicioService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Servicio findById( Long id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Servicio> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Servicio save(Servicio entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Servicio update(Servicio entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Servicio create(Servicio entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Long id );


}
