/*
 * Created on 28 ago 2017 ( Time 17:51:47 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.business.service;

import java.util.List;

import com.tuin.bean.Tipovehiculo;

/**
 * Business Service Interface for entity Tipovehiculo.
 */
public interface TipovehiculoService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Tipovehiculo findById( Long id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Tipovehiculo> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Tipovehiculo save(Tipovehiculo entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Tipovehiculo update(Tipovehiculo entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Tipovehiculo create(Tipovehiculo entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Long id );


}
