/*
 * Created on 28 ago 2017 ( Time 17:51:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.business.service;

import java.util.List;

import com.tuin.bean.Tipocomponentefinanciero;

/**
 * Business Service Interface for entity Tipocomponentefinanciero.
 */
public interface TipocomponentefinancieroService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Tipocomponentefinanciero findById( Long id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Tipocomponentefinanciero> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Tipocomponentefinanciero save(Tipocomponentefinanciero entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Tipocomponentefinanciero update(Tipocomponentefinanciero entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Tipocomponentefinanciero create(Tipocomponentefinanciero entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Long id );


}
