/*
 * Created on 28 ago 2017 ( Time 17:51:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.business.service;

import java.util.List;

import com.tuin.bean.Tipocartera;

/**
 * Business Service Interface for entity Tipocartera.
 */
public interface TipocarteraService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Tipocartera findById( Long id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Tipocartera> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Tipocartera save(Tipocartera entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Tipocartera update(Tipocartera entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Tipocartera create(Tipocartera entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Long id );


}
