/*
 * Created on 28 ago 2017 ( Time 17:51:46 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.business.service;

import java.util.List;

import com.tuin.bean.Tipodocumento;

/**
 * Business Service Interface for entity Tipodocumento.
 */
public interface TipodocumentoService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Tipodocumento findById( Long id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Tipodocumento> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Tipodocumento save(Tipodocumento entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Tipodocumento update(Tipodocumento entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Tipodocumento create(Tipodocumento entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Long id );


}
