/*
 * Created on 28 ago 2017 ( Time 17:51:48 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.business.service;

import java.util.List;

import com.tuin.bean.Vehiculoservicio;

/**
 * Business Service Interface for entity Vehiculoservicio.
 */
public interface VehiculoservicioService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Vehiculoservicio findById( Long id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Vehiculoservicio> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Vehiculoservicio save(Vehiculoservicio entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Vehiculoservicio update(Vehiculoservicio entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Vehiculoservicio create(Vehiculoservicio entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Long id );


}
