/*
 * Created on 28 ago 2017 ( Time 17:50:57 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.persistence.services.fake;

import java.util.List;
import java.util.Map;

import com.tuin.bean.jpa.ClienteviajeservicioEntity;
import com.tuin.persistence.commons.fake.GenericFakeService;
import com.tuin.persistence.services.ClienteviajeservicioPersistence;

/**
 * Fake persistence service implementation ( entity "Clienteviajeservicio" )
 *
 * @author Telosys Tools Generator
 */
public class ClienteviajeservicioPersistenceFAKE extends GenericFakeService<ClienteviajeservicioEntity> implements ClienteviajeservicioPersistence {

	public ClienteviajeservicioPersistenceFAKE () {
		super(ClienteviajeservicioEntity.class);
	}
	
	protected ClienteviajeservicioEntity buildEntity(int index) {
		ClienteviajeservicioEntity entity = new ClienteviajeservicioEntity();
		// Init fields with mock values
		entity.setId( nextLong() ) ;
		entity.setCantidad( nextInteger() ) ;
		return entity ;
	}
	
	
	public boolean delete(ClienteviajeservicioEntity entity) {
		log("delete ( ClienteviajeservicioEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Long id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(ClienteviajeservicioEntity entity) {
		log("insert ( ClienteviajeservicioEntity : " + entity + ")" ) ;
	}

	public ClienteviajeservicioEntity load( Long id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<ClienteviajeservicioEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<ClienteviajeservicioEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<ClienteviajeservicioEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public ClienteviajeservicioEntity save(ClienteviajeservicioEntity entity) {
		log("insert ( ClienteviajeservicioEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<ClienteviajeservicioEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
