/*
 * Created on 28 ago 2017 ( Time 17:50:57 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.persistence.services.fake;

import java.util.List;
import java.util.Map;

import com.tuin.bean.jpa.ColorEntity;
import com.tuin.persistence.commons.fake.GenericFakeService;
import com.tuin.persistence.services.ColorPersistence;

/**
 * Fake persistence service implementation ( entity "Color" )
 *
 * @author Telosys Tools Generator
 */
public class ColorPersistenceFAKE extends GenericFakeService<ColorEntity> implements ColorPersistence {

	public ColorPersistenceFAKE () {
		super(ColorEntity.class);
	}
	
	protected ColorEntity buildEntity(int index) {
		ColorEntity entity = new ColorEntity();
		// Init fields with mock values
		entity.setId( nextLong() ) ;
		entity.setNombre( nextString() ) ;
		entity.setActivo( nextByte() ) ;
		return entity ;
	}
	
	
	public boolean delete(ColorEntity entity) {
		log("delete ( ColorEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Long id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(ColorEntity entity) {
		log("insert ( ColorEntity : " + entity + ")" ) ;
	}

	public ColorEntity load( Long id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<ColorEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<ColorEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<ColorEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public ColorEntity save(ColorEntity entity) {
		log("insert ( ColorEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<ColorEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
