/*
 * Created on 28 ago 2017 ( Time 17:50:57 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.persistence.services.fake;

import java.util.List;
import java.util.Map;

import com.tuin.bean.jpa.ComponentedocumentoEntity;
import com.tuin.persistence.commons.fake.GenericFakeService;
import com.tuin.persistence.services.ComponentedocumentoPersistence;

/**
 * Fake persistence service implementation ( entity "Componentedocumento" )
 *
 * @author Telosys Tools Generator
 */
public class ComponentedocumentoPersistenceFAKE extends GenericFakeService<ComponentedocumentoEntity> implements ComponentedocumentoPersistence {

	public ComponentedocumentoPersistenceFAKE () {
		super(ComponentedocumentoEntity.class);
	}
	
	protected ComponentedocumentoEntity buildEntity(int index) {
		ComponentedocumentoEntity entity = new ComponentedocumentoEntity();
		// Init fields with mock values
		entity.setId( nextLong() ) ;
		return entity ;
	}
	
	
	public boolean delete(ComponentedocumentoEntity entity) {
		log("delete ( ComponentedocumentoEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Long id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(ComponentedocumentoEntity entity) {
		log("insert ( ComponentedocumentoEntity : " + entity + ")" ) ;
	}

	public ComponentedocumentoEntity load( Long id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<ComponentedocumentoEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<ComponentedocumentoEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<ComponentedocumentoEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public ComponentedocumentoEntity save(ComponentedocumentoEntity entity) {
		log("insert ( ComponentedocumentoEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<ComponentedocumentoEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
