/*
 * Created on 28 ago 2017 ( Time 17:50:57 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.persistence.services.fake;

import java.util.List;
import java.util.Map;

import com.tuin.bean.jpa.ComponentefinancieroEntity;
import com.tuin.persistence.commons.fake.GenericFakeService;
import com.tuin.persistence.services.ComponentefinancieroPersistence;

/**
 * Fake persistence service implementation ( entity "Componentefinanciero" )
 *
 * @author Telosys Tools Generator
 */
public class ComponentefinancieroPersistenceFAKE extends GenericFakeService<ComponentefinancieroEntity> implements ComponentefinancieroPersistence {

	public ComponentefinancieroPersistenceFAKE () {
		super(ComponentefinancieroEntity.class);
	}
	
	protected ComponentefinancieroEntity buildEntity(int index) {
		ComponentefinancieroEntity entity = new ComponentefinancieroEntity();
		// Init fields with mock values
		entity.setId( nextLong() ) ;
		entity.setNombre( nextString() ) ;
		entity.setVigenciadesde( nextDate() ) ;
		entity.setVigenciahasta( nextDate() ) ;
		entity.setRubro( nextString() ) ;
		return entity ;
	}
	
	
	public boolean delete(ComponentefinancieroEntity entity) {
		log("delete ( ComponentefinancieroEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Long id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(ComponentefinancieroEntity entity) {
		log("insert ( ComponentefinancieroEntity : " + entity + ")" ) ;
	}

	public ComponentefinancieroEntity load( Long id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<ComponentefinancieroEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<ComponentefinancieroEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<ComponentefinancieroEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public ComponentefinancieroEntity save(ComponentefinancieroEntity entity) {
		log("insert ( ComponentefinancieroEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<ComponentefinancieroEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
