/*
 * Created on 28 ago 2017 ( Time 17:50:58 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.persistence.services.fake;

import java.util.List;
import java.util.Map;

import com.tuin.bean.jpa.DestinohorarioEntity;
import com.tuin.persistence.commons.fake.GenericFakeService;
import com.tuin.persistence.services.DestinohorarioPersistence;

/**
 * Fake persistence service implementation ( entity "Destinohorario" )
 *
 * @author Telosys Tools Generator
 */
public class DestinohorarioPersistenceFAKE extends GenericFakeService<DestinohorarioEntity> implements DestinohorarioPersistence {

	public DestinohorarioPersistenceFAKE () {
		super(DestinohorarioEntity.class);
	}
	
	protected DestinohorarioEntity buildEntity(int index) {
		DestinohorarioEntity entity = new DestinohorarioEntity();
		// Init fields with mock values
		entity.setId( nextLong() ) ;
		entity.setMinimopasajeros( nextInteger() ) ;
		entity.setAutomatico( nextByte() ) ;
		return entity ;
	}
	
	
	public boolean delete(DestinohorarioEntity entity) {
		log("delete ( DestinohorarioEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Long id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(DestinohorarioEntity entity) {
		log("insert ( DestinohorarioEntity : " + entity + ")" ) ;
	}

	public DestinohorarioEntity load( Long id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<DestinohorarioEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<DestinohorarioEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<DestinohorarioEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public DestinohorarioEntity save(DestinohorarioEntity entity) {
		log("insert ( DestinohorarioEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<DestinohorarioEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
