/*
 * Created on 28 ago 2017 ( Time 17:50:59 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.persistence.services.fake;

import java.util.List;
import java.util.Map;

import com.tuin.bean.jpa.FacturaelectronicaEntity;
import com.tuin.persistence.commons.fake.GenericFakeService;
import com.tuin.persistence.services.FacturaelectronicaPersistence;

/**
 * Fake persistence service implementation ( entity "Facturaelectronica" )
 *
 * @author Telosys Tools Generator
 */
public class FacturaelectronicaPersistenceFAKE extends GenericFakeService<FacturaelectronicaEntity> implements FacturaelectronicaPersistence {

	public FacturaelectronicaPersistenceFAKE () {
		super(FacturaelectronicaEntity.class);
	}
	
	protected FacturaelectronicaEntity buildEntity(int index) {
		FacturaelectronicaEntity entity = new FacturaelectronicaEntity();
		// Init fields with mock values
		entity.setId( nextLong() ) ;
		entity.setClaveacceso( nextString() ) ;
		entity.setRespuesta( nextString() ) ;
		entity.setFechaautorizacion( nextDate() ) ;
		return entity ;
	}
	
	
	public boolean delete(FacturaelectronicaEntity entity) {
		log("delete ( FacturaelectronicaEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Long id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(FacturaelectronicaEntity entity) {
		log("insert ( FacturaelectronicaEntity : " + entity + ")" ) ;
	}

	public FacturaelectronicaEntity load( Long id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<FacturaelectronicaEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<FacturaelectronicaEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<FacturaelectronicaEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public FacturaelectronicaEntity save(FacturaelectronicaEntity entity) {
		log("insert ( FacturaelectronicaEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<FacturaelectronicaEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
