/*
 * Created on 28 ago 2017 ( Time 17:51:00 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.persistence.services.fake;

import java.util.List;
import java.util.Map;

import com.tuin.bean.jpa.ItemmenuEntity;
import com.tuin.persistence.commons.fake.GenericFakeService;
import com.tuin.persistence.services.ItemmenuPersistence;

/**
 * Fake persistence service implementation ( entity "Itemmenu" )
 *
 * @author Telosys Tools Generator
 */
public class ItemmenuPersistenceFAKE extends GenericFakeService<ItemmenuEntity> implements ItemmenuPersistence {

	public ItemmenuPersistenceFAKE () {
		super(ItemmenuEntity.class);
	}
	
	protected ItemmenuEntity buildEntity(int index) {
		ItemmenuEntity entity = new ItemmenuEntity();
		// Init fields with mock values
		entity.setId( nextLong() ) ;
		entity.setLink( nextString() ) ;
		entity.setNombre( nextString() ) ;
		entity.setOrden( nextInteger() ) ;
		entity.setActivo( nextByte() ) ;
		return entity ;
	}
	
	
	public boolean delete(ItemmenuEntity entity) {
		log("delete ( ItemmenuEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Long id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(ItemmenuEntity entity) {
		log("insert ( ItemmenuEntity : " + entity + ")" ) ;
	}

	public ItemmenuEntity load( Long id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<ItemmenuEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<ItemmenuEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<ItemmenuEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public ItemmenuEntity save(ItemmenuEntity entity) {
		log("insert ( ItemmenuEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<ItemmenuEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
