/*
 * Created on 28 ago 2017 ( Time 17:51:01 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.persistence.services.fake;

import java.util.List;
import java.util.Map;

import com.tuin.bean.jpa.RolEntity;
import com.tuin.persistence.commons.fake.GenericFakeService;
import com.tuin.persistence.services.RolPersistence;

/**
 * Fake persistence service implementation ( entity "Rol" )
 *
 * @author Telosys Tools Generator
 */
public class RolPersistenceFAKE extends GenericFakeService<RolEntity> implements RolPersistence {

	public RolPersistenceFAKE () {
		super(RolEntity.class);
	}
	
	protected RolEntity buildEntity(int index) {
		RolEntity entity = new RolEntity();
		// Init fields with mock values
		entity.setId( nextLong() ) ;
		entity.setNombre( nextString() ) ;
		entity.setActivo( nextByte() ) ;
		return entity ;
	}
	
	
	public boolean delete(RolEntity entity) {
		log("delete ( RolEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Long id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(RolEntity entity) {
		log("insert ( RolEntity : " + entity + ")" ) ;
	}

	public RolEntity load( Long id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<RolEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<RolEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<RolEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public RolEntity save(RolEntity entity) {
		log("insert ( RolEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<RolEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
