/*
 * Created on 28 ago 2017 ( Time 17:51:38 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.bean;

import java.io.Serializable;

import javax.validation.constraints.*;


public class Chofervehiculo implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Long id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private Long choferid;

    @NotNull
    private Long vehiculoid;

    @NotNull
    private Byte predeterminado;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id ) {
        this.id = id ;
    }

    public Long getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setChoferid( Long choferid ) {
        this.choferid = choferid;
    }
    public Long getChoferid() {
        return this.choferid;
    }

    public void setVehiculoid( Long vehiculoid ) {
        this.vehiculoid = vehiculoid;
    }
    public Long getVehiculoid() {
        return this.vehiculoid;
    }

    public void setPredeterminado( Byte predeterminado ) {
        this.predeterminado = predeterminado;
    }
    public Byte getPredeterminado() {
        return this.predeterminado;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(choferid);
        sb.append("|");
        sb.append(vehiculoid);
        sb.append("|");
        sb.append(predeterminado);
        return sb.toString(); 
    } 


}
