/*
 * Created on 28 ago 2017 ( Time 17:51:40 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.math.BigDecimal;

public class Documento implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Long id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    @Size( min = 1, max = 45 )
    private String numero;

    @NotNull
    @Size( min = 1, max = 45 )
    private String descripcion;

    @NotNull
    private BigDecimal valor;

    @NotNull
    private Long origenid;

    @NotNull
    @Size( min = 1, max = 45 )
    private String origen;

    @NotNull
    private Long estadoid;

    @NotNull
    private Long tipodocumentoid;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id ) {
        this.id = id ;
    }

    public Long getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setNumero( String numero ) {
        this.numero = numero;
    }
    public String getNumero() {
        return this.numero;
    }

    public void setDescripcion( String descripcion ) {
        this.descripcion = descripcion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setValor( BigDecimal valor ) {
        this.valor = valor;
    }
    public BigDecimal getValor() {
        return this.valor;
    }

    public void setOrigenid( Long origenid ) {
        this.origenid = origenid;
    }
    public Long getOrigenid() {
        return this.origenid;
    }

    public void setOrigen( String origen ) {
        this.origen = origen;
    }
    public String getOrigen() {
        return this.origen;
    }

    public void setEstadoid( Long estadoid ) {
        this.estadoid = estadoid;
    }
    public Long getEstadoid() {
        return this.estadoid;
    }

    public void setTipodocumentoid( Long tipodocumentoid ) {
        this.tipodocumentoid = tipodocumentoid;
    }
    public Long getTipodocumentoid() {
        return this.tipodocumentoid;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(numero);
        sb.append("|");
        sb.append(descripcion);
        sb.append("|");
        sb.append(valor);
        sb.append("|");
        sb.append(origenid);
        sb.append("|");
        sb.append(origen);
        sb.append("|");
        sb.append(estadoid);
        sb.append("|");
        sb.append(tipodocumentoid);
        return sb.toString(); 
    } 


}
