/*
 * Created on 28 ago 2017 ( Time 17:51:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.bean;

import java.io.Serializable;

import javax.validation.constraints.*;


public class Entidad implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Long id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    @Size( min = 1, max = 20 )
    private String identificacion;

    @NotNull
    @Size( min = 1, max = 200 )
    private String nombre;

    @Size( max = 200 )
    private String apellido;

    @Size( max = 45 )
    private String correo;

    @Size( max = 45 )
    private String password;

    @NotNull
    private Byte activo;


    private Byte web;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id ) {
        this.id = id ;
    }

    public Long getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setIdentificacion( String identificacion ) {
        this.identificacion = identificacion;
    }
    public String getIdentificacion() {
        return this.identificacion;
    }

    public void setNombre( String nombre ) {
        this.nombre = nombre;
    }
    public String getNombre() {
        return this.nombre;
    }

    public void setApellido( String apellido ) {
        this.apellido = apellido;
    }
    public String getApellido() {
        return this.apellido;
    }

    public void setCorreo( String correo ) {
        this.correo = correo;
    }
    public String getCorreo() {
        return this.correo;
    }

    public void setPassword( String password ) {
        this.password = password;
    }
    public String getPassword() {
        return this.password;
    }

    public void setActivo( Byte activo ) {
        this.activo = activo;
    }
    public Byte getActivo() {
        return this.activo;
    }

    public void setWeb( Byte web ) {
        this.web = web;
    }
    public Byte getWeb() {
        return this.web;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(identificacion);
        sb.append("|");
        sb.append(nombre);
        sb.append("|");
        sb.append(apellido);
        sb.append("|");
        sb.append(correo);
        sb.append("|");
        sb.append(password);
        sb.append("|");
        sb.append(activo);
        sb.append("|");
        sb.append(web);
        return sb.toString(); 
    } 


}
