/*
 * Created on 28 ago 2017 ( Time 17:51:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Facturaelectronica implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Long id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    @Size( min = 1, max = 100 )
    private String claveacceso;

    @NotNull
    private Long estadoid;

    @NotNull
    private Long documentoid;

    @NotNull
    @Size( min = 1, max = 200 )
    private String respuesta;

    @NotNull
    private Date fechaautorizacion;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id ) {
        this.id = id ;
    }

    public Long getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setClaveacceso( String claveacceso ) {
        this.claveacceso = claveacceso;
    }
    public String getClaveacceso() {
        return this.claveacceso;
    }

    public void setEstadoid( Long estadoid ) {
        this.estadoid = estadoid;
    }
    public Long getEstadoid() {
        return this.estadoid;
    }

    public void setDocumentoid( Long documentoid ) {
        this.documentoid = documentoid;
    }
    public Long getDocumentoid() {
        return this.documentoid;
    }

    public void setRespuesta( String respuesta ) {
        this.respuesta = respuesta;
    }
    public String getRespuesta() {
        return this.respuesta;
    }

    public void setFechaautorizacion( Date fechaautorizacion ) {
        this.fechaautorizacion = fechaautorizacion;
    }
    public Date getFechaautorizacion() {
        return this.fechaautorizacion;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(claveacceso);
        sb.append("|");
        sb.append(estadoid);
        sb.append("|");
        sb.append(documentoid);
        sb.append("|");
        sb.append(respuesta);
        sb.append("|");
        sb.append(fechaautorizacion);
        return sb.toString(); 
    } 


}
