/*
 * Created on 28 ago 2017 ( Time 17:51:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.bean;

import java.io.Serializable;

import javax.validation.constraints.*;


public class Formapagodocumento implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Long id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private Long documentoid;

    @NotNull
    private Long formapagoid;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id ) {
        this.id = id ;
    }

    public Long getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setDocumentoid( Long documentoid ) {
        this.documentoid = documentoid;
    }
    public Long getDocumentoid() {
        return this.documentoid;
    }

    public void setFormapagoid( Long formapagoid ) {
        this.formapagoid = formapagoid;
    }
    public Long getFormapagoid() {
        return this.formapagoid;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(documentoid);
        sb.append("|");
        sb.append(formapagoid);
        return sb.toString(); 
    } 


}
