/*
 * Created on 28 ago 2017 ( Time 17:51:38 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.rest.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import com.tuin.bean.Chofervehiculo;
import com.tuin.business.service.ChofervehiculoService;
import com.tuin.web.listitem.ChofervehiculoListItem;

/**
 * Spring MVC controller for 'Chofervehiculo' management.
 */
@Controller
public class ChofervehiculoRestController {

	@Resource
	private ChofervehiculoService chofervehiculoService;
	
	@RequestMapping( value="/items/chofervehiculo",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<ChofervehiculoListItem> findAllAsListItems() {
		List<Chofervehiculo> list = chofervehiculoService.findAll();
		List<ChofervehiculoListItem> items = new LinkedList<ChofervehiculoListItem>();
		for ( Chofervehiculo chofervehiculo : list ) {
			items.add(new ChofervehiculoListItem( chofervehiculo ) );
		}
		return items;
	}
	
	@RequestMapping( value="/chofervehiculo",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<Chofervehiculo> findAll() {
		return chofervehiculoService.findAll();
	}

	@RequestMapping( value="/chofervehiculo/{id}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Chofervehiculo findOne(@PathVariable("id") Long id) {
		return chofervehiculoService.findById(id);
	}
	
	@RequestMapping( value="/chofervehiculo",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Chofervehiculo create(@RequestBody Chofervehiculo chofervehiculo) {
		return chofervehiculoService.create(chofervehiculo);
	}

	@RequestMapping( value="/chofervehiculo/{id}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Chofervehiculo update(@PathVariable("id") Long id, @RequestBody Chofervehiculo chofervehiculo) {
		return chofervehiculoService.update(chofervehiculo);
	}

	@RequestMapping( value="/chofervehiculo/{id}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("id") Long id) {
		chofervehiculoService.delete(id);
	}
	
}
