/*
 * Created on 28 ago 2017 ( Time 17:51:38 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.rest.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import com.tuin.bean.Ciudad;
import com.tuin.business.service.CiudadService;
import com.tuin.web.listitem.CiudadListItem;

/**
 * Spring MVC controller for 'Ciudad' management.
 */
@Controller
public class CiudadRestController {

	@Resource
	private CiudadService ciudadService;
	
	@RequestMapping( value="/items/ciudad",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<CiudadListItem> findAllAsListItems() {
		List<Ciudad> list = ciudadService.findAll();
		List<CiudadListItem> items = new LinkedList<CiudadListItem>();
		for ( Ciudad ciudad : list ) {
			items.add(new CiudadListItem( ciudad ) );
		}
		return items;
	}
	
	@RequestMapping( value="/ciudad",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<Ciudad> findAll() {
		return ciudadService.findAll();
	}

	@RequestMapping( value="/ciudad/{id}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Ciudad findOne(@PathVariable("id") Long id) {
		return ciudadService.findById(id);
	}
	
	@RequestMapping( value="/ciudad",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Ciudad create(@RequestBody Ciudad ciudad) {
		return ciudadService.create(ciudad);
	}

	@RequestMapping( value="/ciudad/{id}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Ciudad update(@PathVariable("id") Long id, @RequestBody Ciudad ciudad) {
		return ciudadService.update(ciudad);
	}

	@RequestMapping( value="/ciudad/{id}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("id") Long id) {
		ciudadService.delete(id);
	}
	
}
