/*
 * Created on 28 ago 2017 ( Time 17:51:43 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.rest.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import com.tuin.bean.Horario;
import com.tuin.business.service.HorarioService;
import com.tuin.web.listitem.HorarioListItem;

/**
 * Spring MVC controller for 'Horario' management.
 */
@Controller
public class HorarioRestController {

	@Resource
	private HorarioService horarioService;
	
	@RequestMapping( value="/items/horario",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<HorarioListItem> findAllAsListItems() {
		List<Horario> list = horarioService.findAll();
		List<HorarioListItem> items = new LinkedList<HorarioListItem>();
		for ( Horario horario : list ) {
			items.add(new HorarioListItem( horario ) );
		}
		return items;
	}
	
	@RequestMapping( value="/horario",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<Horario> findAll() {
		return horarioService.findAll();
	}

	@RequestMapping( value="/horario/{id}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Horario findOne(@PathVariable("id") Long id) {
		return horarioService.findById(id);
	}
	
	@RequestMapping( value="/horario",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Horario create(@RequestBody Horario horario) {
		return horarioService.create(horario);
	}

	@RequestMapping( value="/horario/{id}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Horario update(@PathVariable("id") Long id, @RequestBody Horario horario) {
		return horarioService.update(horario);
	}

	@RequestMapping( value="/horario/{id}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("id") Long id) {
		horarioService.delete(id);
	}
	
}
