/*
 * Created on 28 ago 2017 ( Time 17:51:43 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.rest.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import com.tuin.bean.Itemmenu;
import com.tuin.business.service.ItemmenuService;
import com.tuin.web.listitem.ItemmenuListItem;

/**
 * Spring MVC controller for 'Itemmenu' management.
 */
@Controller
public class ItemmenuRestController {

	@Resource
	private ItemmenuService itemmenuService;
	
	@RequestMapping( value="/items/itemmenu",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<ItemmenuListItem> findAllAsListItems() {
		List<Itemmenu> list = itemmenuService.findAll();
		List<ItemmenuListItem> items = new LinkedList<ItemmenuListItem>();
		for ( Itemmenu itemmenu : list ) {
			items.add(new ItemmenuListItem( itemmenu ) );
		}
		return items;
	}
	
	@RequestMapping( value="/itemmenu",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<Itemmenu> findAll() {
		return itemmenuService.findAll();
	}

	@RequestMapping( value="/itemmenu/{id}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Itemmenu findOne(@PathVariable("id") Long id) {
		return itemmenuService.findById(id);
	}
	
	@RequestMapping( value="/itemmenu",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Itemmenu create(@RequestBody Itemmenu itemmenu) {
		return itemmenuService.create(itemmenu);
	}

	@RequestMapping( value="/itemmenu/{id}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Itemmenu update(@PathVariable("id") Long id, @RequestBody Itemmenu itemmenu) {
		return itemmenuService.update(itemmenu);
	}

	@RequestMapping( value="/itemmenu/{id}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("id") Long id) {
		itemmenuService.delete(id);
	}
	
}
