/*
 * Created on 28 ago 2017 ( Time 17:51:45 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.rest.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import com.tuin.bean.Rolitemmenu;
import com.tuin.business.service.RolitemmenuService;
import com.tuin.web.listitem.RolitemmenuListItem;

/**
 * Spring MVC controller for 'Rolitemmenu' management.
 */
@Controller
public class RolitemmenuRestController {

	@Resource
	private RolitemmenuService rolitemmenuService;
	
	@RequestMapping( value="/items/rolitemmenu",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<RolitemmenuListItem> findAllAsListItems() {
		List<Rolitemmenu> list = rolitemmenuService.findAll();
		List<RolitemmenuListItem> items = new LinkedList<RolitemmenuListItem>();
		for ( Rolitemmenu rolitemmenu : list ) {
			items.add(new RolitemmenuListItem( rolitemmenu ) );
		}
		return items;
	}
	
	@RequestMapping( value="/rolitemmenu",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<Rolitemmenu> findAll() {
		return rolitemmenuService.findAll();
	}

	@RequestMapping( value="/rolitemmenu/{id}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Rolitemmenu findOne(@PathVariable("id") Long id) {
		return rolitemmenuService.findById(id);
	}
	
	@RequestMapping( value="/rolitemmenu",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Rolitemmenu create(@RequestBody Rolitemmenu rolitemmenu) {
		return rolitemmenuService.create(rolitemmenu);
	}

	@RequestMapping( value="/rolitemmenu/{id}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Rolitemmenu update(@PathVariable("id") Long id, @RequestBody Rolitemmenu rolitemmenu) {
		return rolitemmenuService.update(rolitemmenu);
	}

	@RequestMapping( value="/rolitemmenu/{id}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("id") Long id) {
		rolitemmenuService.delete(id);
	}
	
}
