/*
 * Created on 28 ago 2017 ( Time 17:51:48 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.rest.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import com.tuin.bean.Viaje;
import com.tuin.business.service.ViajeService;
import com.tuin.web.listitem.ViajeListItem;

/**
 * Spring MVC controller for 'Viaje' management.
 */
@Controller
public class ViajeRestController {

	@Resource
	private ViajeService viajeService;
	
	@RequestMapping( value="/items/viaje",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<ViajeListItem> findAllAsListItems() {
		List<Viaje> list = viajeService.findAll();
		List<ViajeListItem> items = new LinkedList<ViajeListItem>();
		for ( Viaje viaje : list ) {
			items.add(new ViajeListItem( viaje ) );
		}
		return items;
	}
	
	@RequestMapping( value="/viaje",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<Viaje> findAll() {
		return viajeService.findAll();
	}

	@RequestMapping( value="/viaje/{id}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Viaje findOne(@PathVariable("id") Long id) {
		return viajeService.findById(id);
	}
	
	@RequestMapping( value="/viaje",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Viaje create(@RequestBody Viaje viaje) {
		return viajeService.create(viaje);
	}

	@RequestMapping( value="/viaje/{id}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Viaje update(@PathVariable("id") Long id, @RequestBody Viaje viaje) {
		return viajeService.update(viaje);
	}

	@RequestMapping( value="/viaje/{id}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("id") Long id) {
		viajeService.delete(id);
	}
	
}
