/*
 * Created on 28 ago 2017 ( Time 17:51:16 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.tuin.bean.Horario;
import com.tuin.bean.jpa.HorarioEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class HorarioServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public HorarioServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'HorarioEntity' to 'Horario'
	 * @param horarioEntity
	 */
	public Horario mapHorarioEntityToHorario(HorarioEntity horarioEntity) {
		if(horarioEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Horario horario = map(horarioEntity, Horario.class);

		return horario;
	}
	
	/**
	 * Mapping from 'Horario' to 'HorarioEntity'
	 * @param horario
	 * @param horarioEntity
	 */
	public void mapHorarioToHorarioEntity(Horario horario, HorarioEntity horarioEntity) {
		if(horario == null) {
			return;
		}

		//--- Generic mapping 
		map(horario, horarioEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}