/*
 * Created on 28 ago 2017 ( Time 17:51:19 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.tuin.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.tuin.bean.Tipovehiculo;
import com.tuin.bean.jpa.TipovehiculoEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class TipovehiculoServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public TipovehiculoServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'TipovehiculoEntity' to 'Tipovehiculo'
	 * @param tipovehiculoEntity
	 */
	public Tipovehiculo mapTipovehiculoEntityToTipovehiculo(TipovehiculoEntity tipovehiculoEntity) {
		if(tipovehiculoEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Tipovehiculo tipovehiculo = map(tipovehiculoEntity, Tipovehiculo.class);

		return tipovehiculo;
	}
	
	/**
	 * Mapping from 'Tipovehiculo' to 'TipovehiculoEntity'
	 * @param tipovehiculo
	 * @param tipovehiculoEntity
	 */
	public void mapTipovehiculoToTipovehiculoEntity(Tipovehiculo tipovehiculo, TipovehiculoEntity tipovehiculoEntity) {
		if(tipovehiculo == null) {
			return;
		}

		//--- Generic mapping 
		map(tipovehiculo, tipovehiculoEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}